### ISSUE TITLE
Clarifying Questions

### ISSUE THREAD

**Issue by Asmodeux2** [codekulturbonn/espocto#2]
---
# Clarifying Questions

### 3. I'm also quite confused about the file for connecting to WiFi. For what purpose does the device need a connection to WiFi? Is it for adding or deleting files through LittleFS or SDCard? 📶💻
---

**Comment by Asmodeux2** [comment]
You're welcome for creating this port and repository! I'm glad to help. If you have any more questions or need further assistance, feel free to ask. 😊💻

**Comment by oschettler** [comment]
1. #1 Please include the Bootloader and Partitions in the release as well. 📥

done.

2. I'm also quite confused about the chip8.txt file. Could you please explain it in more detail? 📝

This is, in fact, no longer used. The README contained stale information. I have updated it. 

Rather than using a separate file (chip8.txt), at some point I decided to invent a new file format *.ec8 which has some options prepended before the actual CHIP8 data. Ultimately, I would have loved to support John Earnest's *.gif files, but I shied away from the processing required to extract the game data on the ESP32.

3. I'm also quite confused about the file for connecting to WiFi. For what purpose does the device need a connection to WiFi? Is it for adding or deleting files through LittleFS or SDCard? 📶💻

This is very much work in (slow, I admit) progress. My goal for this project is to create a gadget which allows writing code as well as playing games. The on-device memory editor and disassembler is a first step. With the web server, the idea was to create a simple IDE as a web form which could be used from eg. a mobile device. However, the code for this is yet to be written. First experiments proved difficult: I had some problems fitting the code into the memory of the device.

**Comment by Asmodeux2** [comment]
Actually your project is very cool. I'm very grateful for your hard work

**Comment by Asmodeux2** [comment]
Actually your project is very cool. I'm very grateful for your hard work
